// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvbhXkxo5fUFAliHIIGzq-EEZvGed_8UU',
    appId: '1:26970932099:web:4bf08a6fd072165dc36cb6',
    messagingSenderId: '26970932099',
    projectId: 'kissan-connect-324ee',
    authDomain: 'kissan-connect-324ee.firebaseapp.com',
    storageBucket: 'kissan-connect-324ee.firebasestorage.app',
    measurementId: 'G-74LQ7E7LY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsYhI5b63Xtoz14AsW9EFea1xiHU7k_L0',
    appId: '1:26970932099:android:51d9ee0d2be2d666c36cb6',
    messagingSenderId: '26970932099',
    projectId: 'kissan-connect-324ee',
    storageBucket: 'kissan-connect-324ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB29x9TdAHaJr04pHeiWCzpcLinEmQMaYc',
    appId: '1:26970932099:ios:46be5b978ce2a95cc36cb6',
    messagingSenderId: '26970932099',
    projectId: 'kissan-connect-324ee',
    storageBucket: 'kissan-connect-324ee.firebasestorage.app',
    iosBundleId: 'com.example.kissanconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB29x9TdAHaJr04pHeiWCzpcLinEmQMaYc',
    appId: '1:26970932099:ios:46be5b978ce2a95cc36cb6',
    messagingSenderId: '26970932099',
    projectId: 'kissan-connect-324ee',
    storageBucket: 'kissan-connect-324ee.firebasestorage.app',
    iosBundleId: 'com.example.kissanconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvbhXkxo5fUFAliHIIGzq-EEZvGed_8UU',
    appId: '1:26970932099:web:40e4165df0af0090c36cb6',
    messagingSenderId: '26970932099',
    projectId: 'kissan-connect-324ee',
    authDomain: 'kissan-connect-324ee.firebaseapp.com',
    storageBucket: 'kissan-connect-324ee.firebasestorage.app',
    measurementId: 'G-M0CMRXS6RT',
  );
}
